package net.strinka.strinkout

class Exercise {
    val name: String

    constructor(name: String) {
        this.name = name
    }
}

//Note: the index of this list is used an a unique identifier. Only add to the end, don't change the order.
val allExercises = listOf(
    Exercise("Abdominal Crunch"),
    Exercise("Alternating Push-up Plank"),
    Exercise("Back Leg Raise"),
    Exercise("Bent Leg Twist"),
    Exercise("Burpees"),
    Exercise("Butt Kickers"),
    Exercise("Calf Raises"),
    Exercise("Chest Expander"),
    Exercise("Diamond Push-ups"),
    Exercise("Dive Bomber Push-ups"),
    Exercise("Elevated Crunches"),
    Exercise("Forward Lunges"),
    Exercise("Frog Jumps"),
    Exercise("Front Kicks"),
    Exercise("Genie Sit"),
    Exercise("High Jumper"),
    Exercise("High Knees"),
    Exercise("Hip Raise"),
    Exercise("In and Out Abs"),
    Exercise("Inch Worms"),
    Exercise("Jump Rope Hops"),
    Exercise("Jump Squats"),
    Exercise("Jumping Jacks"),
    Exercise("Jumping Planks"),
    //Exercise("Lateral Pillar Bridge"),
    Exercise("Lateral Squats"),
    Exercise("Leg Lifts"),
    Exercise("Leg Spreaders"),
    Exercise("Lying Tricep Lifts"),
    Exercise("Mason Twist"),
    Exercise("Mountain Climbers"),
    //Exercise("One Arm Side Push-up"),
    //Exercise("One Leg Circles"),
    Exercise("Overhead Arm Clap"),
    Exercise("Overhead Press"),
    Exercise("Plank"),
    Exercise("Plank with Arm Lift"),
    Exercise("Pivoting Upper Cuts"),
    Exercise("Power Circles"),
    Exercise("Power Jump"),
    Exercise("Push-up and Rotation"),
    Exercise("Push-up on Knees"),
    Exercise("Push-ups"),
    Exercise("Quadruplex"),
    Exercise("Reach Throughs"),
    Exercise("Reach Ups"),
    Exercise("Rear Lunges"),
    Exercise("Reverse Plank"),
    Exercise("Reverse V Lunges"),
    Exercise("Running in Place"),
    Exercise("Scissor Kicks"),
    Exercise("Shoulder Tap Push-ups"),
    //Exercise("Side Bridge"),
    //Exercise("Side Circles"),
    Exercise("Side Hops"),
    //Exercise("Side Leg Lifts"),
    Exercise("Side Squats"),
    Exercise("Side to Side Knee Lifts"),
    //Exercise("Single Leg Hops"),
    //Exercise("Single Leg Squats"),
    Exercise("Sit-ups"),
    Exercise("Six Inches and Hold"),
    Exercise("Spiderman Push-up"),
    Exercise("Sprinter"),
    Exercise("Squat Jabs"),
    Exercise("Squat Jacks"),
    Exercise("Squat with Back Kick"),
    Exercise("Squats"),
    Exercise("Standing Side Crunch"),
    Exercise("Steam Engine"),
    Exercise("Step Touch"),
    Exercise("Supermans"),
    Exercise("Supine Bicycle"),
    Exercise("Swimmer"),
    Exercise("Switch Kick"),
    Exercise("T Raise"),
    Exercise("Teaser"),
    Exercise("Tricep Dips"),
    Exercise("Twisting Crunches"),
    Exercise("Up Downs"),
    Exercise("V Balance"),
    Exercise("V Sit-ups"),
    Exercise("Vertical Arm Rotations"),
    Exercise("Wall Push-ups"),
    Exercise("Wall Sit"),
    Exercise("Wide Arm Push-ups"),
    Exercise("Wide Squats"),
    Exercise("Windmill")
)

